### ISSUE TITLE
Add config option to have mod affect Huntress' Flurry

### ISSUE THREAD

**Issue by rehashedsalt** [ThinkInvis/RoR2-Hypercrit#2]
If I had a dev environment built up for R2API, I'd just do it myself and just PR, but I'm short on time and also don't want to boot up a Windows VM just for Visual Studio.

So you know how Huntress' new Primary - Flurry - does that thing where it fires 6 arrows instead of 3 on any shot that rolls a critical hit? What if you made *that* scale with hyper crits, too?

Just think about how face-meltingly, computer-crashingly fun a 200-arrow burst would be. It'd make for a really fun Huntress meme build.

**Comment by ThinkInvis** [comment]
That's easier said than done, due to how RoR2 handles crits. The crit chance is rolled as soon as the attack is fired... and then that bool gets passed around through a bajillion different methods. The best I could do was to hook into HealthComponent.TakeDamage and add crit damage based on a second roll versus the attacker's crit chance. Making this line up with the number of projectiles Flurry fires would require somehow injecting a new variable (number of stacked crits) into every link in the chain between them, and I'm not sure how to approach that.

**Comment by ThinkInvis** [comment]
I may have a way around this now; I'll close and mark as cantfix if it doesn't pan out.

**Comment by ThinkInvis** [comment]
Fixed by 27466bb0404d2148ff20eaeddfaa804f6c280ed6.
